/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dedosjr
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Opciones = new javax.swing.JMenu();
        Suma = new javax.swing.JMenu();
        digito1 = new javax.swing.JMenuItem();
        digito2 = new javax.swing.JMenuItem();
        Digitos3 = new javax.swing.JMenuItem();
        Resta = new javax.swing.JMenu();
        Restadigitos1 = new javax.swing.JMenuItem();
        RestaDigitos2 = new javax.swing.JMenuItem();
        RestaDigitos3 = new javax.swing.JMenuItem();
        Multiplicacion = new javax.swing.JMenu();
        MultiplicacionDigito1 = new javax.swing.JMenuItem();
        MultiplicacionDigitos2 = new javax.swing.JMenuItem();
        MultiplicacionDigitos3 = new javax.swing.JMenuItem();
        Division = new javax.swing.JMenu();
        divisiondigito1 = new javax.swing.JMenuItem();
        divisiondigitos2 = new javax.swing.JMenuItem();
        divisiondigitos3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Opciones.setText("Opciones");

        Suma.setText("Suma");

        digito1.setText("Suma 1 digito");
        digito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digito1ActionPerformed(evt);
            }
        });
        Suma.add(digito1);

        digito2.setText("Suma 2 digitos");
        digito2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digito2ActionPerformed(evt);
            }
        });
        Suma.add(digito2);

        Digitos3.setText("Suma 3 digitos");
        Digitos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Digitos3ActionPerformed(evt);
            }
        });
        Suma.add(Digitos3);

        Opciones.add(Suma);

        Resta.setText("Resta");

        Restadigitos1.setText("Resta 1 digito");
        Restadigitos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restadigitos1ActionPerformed(evt);
            }
        });
        Resta.add(Restadigitos1);

        RestaDigitos2.setText("Resta 2 digitos");
        RestaDigitos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaDigitos2ActionPerformed(evt);
            }
        });
        Resta.add(RestaDigitos2);

        RestaDigitos3.setText("Resta 3 digitos");
        RestaDigitos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaDigitos3ActionPerformed(evt);
            }
        });
        Resta.add(RestaDigitos3);

        Opciones.add(Resta);

        Multiplicacion.setText("Multiplicacion");

        MultiplicacionDigito1.setText("Multiplicacion 1 digito");
        MultiplicacionDigito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicacionDigito1ActionPerformed(evt);
            }
        });
        Multiplicacion.add(MultiplicacionDigito1);

        MultiplicacionDigitos2.setText("Multiplicacion 2 digitos");
        MultiplicacionDigitos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicacionDigitos2ActionPerformed(evt);
            }
        });
        Multiplicacion.add(MultiplicacionDigitos2);

        MultiplicacionDigitos3.setText("Multiplicacion 3 digitos");
        MultiplicacionDigitos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicacionDigitos3ActionPerformed(evt);
            }
        });
        Multiplicacion.add(MultiplicacionDigitos3);

        Opciones.add(Multiplicacion);

        Division.setText("Division");

        divisiondigito1.setText("Division 1 digito");
        divisiondigito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisiondigito1ActionPerformed(evt);
            }
        });
        Division.add(divisiondigito1);

        divisiondigitos2.setText("Division 2 digitos");
        divisiondigitos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisiondigitos2ActionPerformed(evt);
            }
        });
        Division.add(divisiondigitos2);

        divisiondigitos3.setText("Division 3 digitos");
        divisiondigitos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisiondigitos3ActionPerformed(evt);
            }
        });
        Division.add(divisiondigitos3);

        Opciones.add(Division);

        jMenuBar1.add(Opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void digito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digito1ActionPerformed
        // TODO add your handling code here:
        Suma ventana = new Suma();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_digito1ActionPerformed

    private void MultiplicacionDigito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionDigito1ActionPerformed
        // TODO add your handling code here:
         Multiplicacion ventana = new Multiplicacion();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MultiplicacionDigito1ActionPerformed

    private void Restadigitos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restadigitos1ActionPerformed
        // TODO add your handling code here:
        Resta ventana = new Resta();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_Restadigitos1ActionPerformed

    private void divisiondigito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisiondigito1ActionPerformed
        // TODO add your handling code here:
        Division ventana = new Division();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_divisiondigito1ActionPerformed

    private void digito2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digito2ActionPerformed
        // TODO add your handling code here:
         SumaDigitos2 ventana = new SumaDigitos2();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_digito2ActionPerformed

    private void Digitos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Digitos3ActionPerformed
        // TODO add your handling code here:
         SumaDigitos3 ventana = new SumaDigitos3();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_Digitos3ActionPerformed

    private void RestaDigitos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaDigitos3ActionPerformed
        // TODO add your handling code here:
        RestaDigitos3 ventana = new RestaDigitos3();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_RestaDigitos3ActionPerformed

    private void RestaDigitos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaDigitos2ActionPerformed
        // TODO add your handling code here:
        Restadigitos2 ventana = new Restadigitos2();
        Escritorio.add(ventana);
        ventana.show();
        
    }//GEN-LAST:event_RestaDigitos2ActionPerformed

    private void MultiplicacionDigitos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionDigitos2ActionPerformed
        // TODO add your handling code here:
         MultiplicacionDigitos2 ventana = new MultiplicacionDigitos2();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MultiplicacionDigitos2ActionPerformed

    private void MultiplicacionDigitos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionDigitos3ActionPerformed
        // TODO add your handling code here:
        MultiplicacionDigitos3 ventana = new MultiplicacionDigitos3();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_MultiplicacionDigitos3ActionPerformed

    private void divisiondigitos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisiondigitos2ActionPerformed
        // TODO add your handling code here:
        DivisionDigitos2 ventana = new DivisionDigitos2();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_divisiondigitos2ActionPerformed

    private void divisiondigitos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisiondigitos3ActionPerformed
        // TODO add your handling code here:
        DivisionDigitos3 ventana = new DivisionDigitos3();
        Escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_divisiondigitos3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Digitos3;
    private javax.swing.JMenu Division;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu Multiplicacion;
    private javax.swing.JMenuItem MultiplicacionDigito1;
    private javax.swing.JMenuItem MultiplicacionDigitos2;
    private javax.swing.JMenuItem MultiplicacionDigitos3;
    private javax.swing.JMenu Opciones;
    private javax.swing.JMenu Resta;
    private javax.swing.JMenuItem RestaDigitos2;
    private javax.swing.JMenuItem RestaDigitos3;
    private javax.swing.JMenuItem Restadigitos1;
    private javax.swing.JMenu Suma;
    private javax.swing.JMenuItem digito1;
    private javax.swing.JMenuItem digito2;
    private javax.swing.JMenuItem divisiondigito1;
    private javax.swing.JMenuItem divisiondigitos2;
    private javax.swing.JMenuItem divisiondigitos3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
